const products = [
  {
    id: 1,
    url: "assets/img/products/banana-maple-front.jpg",
    title: "Banana Maple",
    price: 1000,
    type: "grain free",
    favourite: true,
  },
  {
    id: 2,
    url: "assets/img/products/chocchia-front.jpg",
    title: "Chocolate Chia",
    price: 2000,
    type: "grain free",
    favourite: true,
  },
  {
    id: 3,
    url: "assets/img/products/nutseed-front.jpg",
    title: "Original Nut y Seed",
    price: 2500,
    type: "grain free",
    favourite: true,
  },
  {
    id: 4,
    url: "assets/img/products/pbj-front.jpg",
    title: "Peanut Butter y Jelly",
    price: 3000,
    type: "snacks",
    favourite: true,
  },
  {
    id: 5,
    url: "assets/img/products/pbc-front.jpg",
    title: "Peanut Butter Chocolate",
    price: 500,
    type: "snacks",
    favourite: true,
  },
  {
    id: 6,
    url: "assets/img/products/vtm-front-newsize.jpg",
    title: "Vegan Trail Mix",
    price: 800,
    type: "snacks",
    favourite: true,
  },
  {
    id: 7,
    url: "assets/img/products/vg-front.jpg",
    title: "Vanilla Ginger",
    price: 2500,
    type: "snacks",
    favourite: true,
  },
  {
    id: 8,
    url: "assets/img/products/rv-front.jpg",
    title: "Red Velvet Cookie Bites",
    price: 1500,
    type: "cookie bites",
    favourite: true,
  },
  {
    id: 9,
    url: "assets/img/products/almond-front.jpg",
    title: "Almond Butter",
    price: 1800,
    type: "cookie bites",
    favourite: false,
  },
  {
    id: 10,
    url: "assets/img/products/ps-front.jpg",
    title: "Pumpkin Spice",
    price: 1900,
    type: "cookie bites",
    favourite: false,
  },
  {
    id: 11,
    url: "assets/img/products/BananaBread_Front.png",
    title: "Banana Bread",
    price: 3900,
    type: "grain free",
    favourite: false,
  },
  {
    id: 12,
    url: "assets/img/products/SweetPotato_Front.png",
    title: "Sweet Potato Pie",
    price: 2900,
    type: "grain free",
    favourite: false,
  },
];

export { products };
